# Generated by Django 5.1.3 on 2024-12-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FuelSensor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geofence",
            name="coordinates",
        ),
        migrations.AddField(
            model_name="geofence",
            name="lat",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="geofence",
            name="lng",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="geofence",
            name="radius",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
